---
title: "Data Import"
output: github_document
---

This file is for doing data import.

## Import two .csv files
```{r}
library("tidyverse")
library("readxl")
```

Import our first dataset.

```{r}
litters_df = 
  read.csv(file = "data/FAS_litters.csv",
           na = c(" ", ".", "NA"))

litters_df = janitor::clean_names(litters_df)
```

Import the second dataset
```{r}
pups_df = 
  read.csv(file = "data/FAS_pups.csv",
           skip = 3,
           na = c(" ", ".", "NA"))

pups_df = janitor::clean_names(pups_df)
```


## Look at the data
```{r}
litters_df
pups_df
```

Head or tail
```{r}
head(litters_df, 20)

tail(pups_df, 5)
```

Skimming?
```{r}
skimr::skim(pups_df)
```


## Oh Excel....

Jenny Bryan made `readxl` to solve the problems

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

Look at the data 
mlb_df

Import FOTR words.

```{r}
fotr_df = 
  read_excel("data/LotR_Words.xlsx",
             range = "B3:D6")

fotr_df
```

```{r}
tt_df = 
  read_excel("data/LotR_Words.xlsx",
             range = "F3:H6")

tt_df
```

